import { useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  let router = useRouter();
  useEffect(() => {
    setTimeout(() => {
      router.push("/home");
    }, 2000);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Al Aqsa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Image src={"/img.png"} layout="fill" />
      </div>
    </div>
  );
}
